Cpu refactoring
subspace/sloth256-189 pull request #6
Opened 2021-09-10 08:14 UTC by ozgunozerk

2021-09-12 11:52 UTC, nazar-pc requested changes
Please move all CPU-related code into `cpu` folder, not just two Rust files.

2021-09-13 08:03 UTC, ozgunozerk commented
> Please move all CPU-related code into `cpu` folder, not just two Rust files.

Yes, we did that with the cuda-ptx branch. I reflected the same changes to this branch now, as it should have been :)

2021-09-13 09:17 UTC, nazar-pc reviewed
Looks good otherwise

2021-09-13 09:17 UTC, nazar-pc commented on implementation.md
> +by Linux, *BSD, Solaris) or `cpu.mach-o` (used by MacOS) executable formats.
Please fix these

2021-09-13 09:54 UTC, nazar-pc approved these changes

2021-09-13 09:55 UTC, merged